[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "game_bots"
description = "Python package for 2048 wrapper from Julia."
version = "0.1.0"

readme = "README.md"

dependencies = ["numpy~=1.23.4", "julia~=0.6.1", "torch", "deap~=1.3.3"]
